item {
  id: 1
  name: 'dur'
}

item {
  id: 2
  name: 'durak'
}

item {
  id: 3
  name: 'gec'
}

item {
  id: 4
  name: 'giris_yasak'
}

item {
  id: 5
  name: 'hiz_otuz'
}

item {
  id: 6
  name: 'hiz_yirmi'
}

item {
  id: 7
  name: 'park'
}

item {
  id: 8
  name: 'park_yasak'
}

item {
  id: 9
  name: 'sag_ileriden'
}

item {
  id: 10
  name: 'sag_yasak'
}

item {
  id: 11
  name: 'sol_ileriden'
}

item {
  id: 12
  name: 'sol_yasak'
}

item {
  id: 13
  name: 'trafige_kapali'
}

item {
  id: 14
  name: 'yirmi_son'
}